# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jonny Cheng
email: jonnycheng6@gmail.com
description: > # it is jonny's blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://127.0.0.1:4000/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Navigation
nav:
  - name:           "About"
    href:           "/about"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# Gems
gems: [jekyll-paginate]
paginate: 10
paginate_path: "blog/page:num"

# comments
comments: true